#' Integrated Transport and Health Impacts Model (ITHIM)
#'
#' Implementation in R
#' 
#' @name ITHIM-package
#' @docType package
#' @author Samuel G. Younkin \email{syounkin@@wisc.edu}
#' @seealso \code{\link{createParameterList}}, \code{\link{computeMeanMatrices}}
#' @examples
#'
#' ITHIMParameterList <- createParameterList()
#' meansList <- computeMeanMatrices(ITHIMParameterList)
#' names(meansList)
#' meansList$meanActiveTransportTime
#' 
NULL
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' This function coverts the 2001 CDC Age variable to years.
#'
#' @param value The value for age, i.e., characters 2-4 of the code
#'     (sloppy with class!)
#' @param unit The units for age, i.e., chatater 1 of the code (sloppy
#'     with class!)
#' @note This function is likely only applicable to the 2001 data
#'     file.
#' @return A numeric vector of age in years - this is a test
#' 
#' @export
convertAge <- function(value, unit){

    value <- ifelse(value == "999", NA, value)

    convertedValue <- ifelse( unit == "1", value,
    ifelse( unit == "2", value/12,
    ifelse( unit == "4", value/365,
    ifelse( unit == "5", value/365/24,
    ifelse( unit == "6", value/365/24/60,
    ifelse( unit == "9", NA, 999 ))))))

    return(as.numeric(convertedValue))

}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Create a list of input parameters
#'
#' @return A list with parameters and estimates
#'
#' \item{F}{A numerical matrix for the population density, stratified by age class and sex}
#' \item{Rwt}{A numerical matrix for the walking time, relative to ?value?}
#' \item{Rws}{A numerical matrix for the walking speed, relative to ?value?}
#' \item{Rct}{A numerical matrix for the cycling time, relative to ?value?}
#' \item{Rcs}{A numerical matrix for the cycling speed, relative to ?value?}
#' \item{muwt}{A numerical value for the mean walking time}
#' \item{muws}{A numerical value for the mean walking speed}
#' \item{muct}{A numerical value for the mean cycling time}
#' \item{mucs}{A numerical value for the mean cycling speed}
#' \item{cv}{A numerical value for the coefficient of variation for active transport time}
#'
#' @note A note about the default values.
#'
#' 
#' @export
createParameterList <- function(){

    nAgeClass <- 8
    
    F <- matrix(c(0.0368276992,0.0353723566,0.0746989673,0.0716902674,0.1123490977,0.1104366009,0.1163649132,0.1182206842,0.0808260989,0.0891264801,0.0308720468,0.037493344,0.0223834475,0.0321797163,0.0098989332,0.0212593465), byrow = TRUE, nrow = nAgeClass, ncol = 2, dimnames = list(paste0("ageClass",1:nAgeClass),c("M","F")))

    Rwt <- matrix(c(0.43053,0.34715,0.49337,0.48135,0.93248,1.00000,0.76528,0.73350,0.68250,0.65805,0.56376,0.77155,0.58923,0.62678,0.56524,0.39604),byrow=TRUE, ncol = 2, dimnames = list(paste0("ageClass",1:nAgeClass),c("M","F")))

    Rct <- matrix(c(0.29350,0.12305,1.31944,0.82780,1.86938,1.00000,1.56016,0.73770,1.45792,0.24667,0.45162,0.18923,0.49021,0.16502,0.07503,0.02941),byrow=TRUE, ncol = 2, dimnames = list(paste0("ageClass",1:nAgeClass),c("M","F")))

    Rws <- matrix(c(1.06625,0.87533,1.06625,0.87533,1.02062,1.00021,1.05905,1.03383,1.03923,0.94738,1.03023,0.93297,0.95098,0.89695,0.95098,0.89695),byrow=TRUE, ncol = 2, dimnames = list(paste0("ageClass",1:nAgeClass),c("M","F")))

    Rcs <- matrix(c(0.847395,0.837454,0.892011,0.981718,1.072100,0.956966,1.073487,0.980472,1.156495,0.962792,1.063072,0.929156,1.029339,0.848509,0.902283,0.830812),byrow=TRUE, ncol = 2, dimnames = list(paste0("ageClass",1:nAgeClass),c("M","F")))

    muwt <- 54.4 # min per week
    muws <- 2.7 # mph
    muct <- 9.7 # min per week
    mucs <- 7.4 # mph

    cv <- 1.723 # coefficient of variation

    #meanTw.Mat <- muwt/alphawt*Rwt
    
    return(list(F = F, Rwt = Rwt, Rws = Rws, Rct = Rct, Rcs = Rcs, muwt = muwt, muws = muws, muct = muct, mucs = mucs, cv = cv, nAgeClass = nAgeClass))

}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Compute Matrices of Active Transport Means
#'
#' This function computes mean walking/cycling time/speed, as well as
#' active transport METs mean and standard deviation
#'
#' @param parList The list of parameters generated by
#'     \code{\link{createParameterList}}
#' 
#' @return A list with matrices of means
#'
#' \item{meanWalkTime}{A numerical matrix of mean weekly time (hours?) for walking as transport}
#' \item{meanWalkSpeed}{A numerical matrix of mean weekly speed for walking as transport}
#' \item{meanCycleTime}{A numerical matrix of mean weekly time for cycling as transport}
#' \item{meanCycleSpeed}{A numerical matrix of mean weekly speed for cycling as transport}
#' \item{meanWalkMET}{A numerical matrix of mean weekly METs for walking as transport}
#' \item{meanCycleMET}{A numerical matrix of mean weekly METs for cycling as transport}
#' \item{meanActiveTransportTime}{A numerical matrix containing mean weekly active transport time}
#' \item{sdActiveTransportTime}{A numerical matrix containing standard deviation of weekly active transport time}
#' \item{propTimeCycling}{The proportion of time walking out of walking or cycling as active transport}
#'
#' @note Currently all age by sex classes are assigned 6 for weekly
#'     cycling for transport METs.  This means we assume that, unlike
#'     walking, cycling energy is not a function of speed.
#' 
#' @seealso \code{\link{createParameterList}}, \code{\link{ITHIM-package}}
#' 
#' @export
computeMeanMatrices <- function(parList){
    with(parList, {
        alphawt <- sum(F*Rwt)
        alphact <- sum(F*Rct)
        alphaws <- sum(F*Rws)
        alphacs <- sum(F*Rcs)
        meanWalkTime <- muwt/alphawt*Rwt
        meanCycleTime <- muct/alphact*Rct
        propTimeCycling <-  meanCycleTime/(meanCycleTime+meanWalkTime)
        meanWalkSpeed <- muws/alphaws*Rws
        meanCycleSpeed <- mucs/alphacs*Rcs
        meanWalkMET <- ifelse(1.2216*meanWalkSpeed + 0.0838 < 2.5, 2.5,  1.2216*meanWalkSpeed + 0.0838)
        meanCycleMET <- matrix(6, byrow=TRUE, ncol = 2, nrow =nrow(F),dimnames = list(paste0("ageClass",1:nAgeClass),c("M","F")))
        meanActiveTransportTime <- meanWalkTime + meanCycleTime
        sdActiveTransportTime <- meanActiveTransportTime*cv
        
        return(list(meanWalkTime = meanWalkTime, meanCycleTime = meanCycleTime, meanWalkSpeed = meanWalkSpeed, meanCycleSpeed = meanCycleSpeed, meanWalkMET = meanWalkMET, meanCycleMET = meanCycleMET, meanActiveTransportTime = meanActiveTransportTime, sdActiveTransportTime = sdActiveTransportTime, propTimeCycling = propTimeCycling))
        })
}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Compute Quintiles of the Lognormal Distribution
#'
#' Compute quintiles of the lognormal distribution given matrices for
#' mean and standard deviation of active transport time.  This
#' function is used by the function \code{\link{getQuintiles}}
#'
#' @param mean A numerical matrix of means for active transport time
#' @param sd A numerical matrix of standard deviations for active
#'     transport time
#' 
#' @return A vector of quintiles
#'
#' @note This function needs to be cleaned up so it is more user
#'     friendly
#' @note Quintiles are defined as 10, 30, 50, 70, 90 percentiles
#'
#' @seealso \code{\link{getQuintiles}}
#' 
#' @export
computeQuintiles <- function( mean, sd ){

    nAgeClass <- nrow(mean)
    ncol <- 5
    
    logMean <- log(mean)-1/2*log(1+(sd/mean)^2)
    logSD <- sqrt(log(1+(sd/mean)^2))

    quintVec <- c(mapply(qlnorm, logMean, logSD, p = 0.1),
    mapply(qlnorm, logMean, logSD, p = 0.3),
    mapply(qlnorm, logMean, logSD, p = 0.5),
    mapply(qlnorm, logMean, logSD, p = 0.7),
    mapply(qlnorm, logMean, logSD, p = 0.9))

    quintMat <- matrix(quintVec, nrow = 2*nAgeClass, ncol = ncol, dimnames = list(paste0("ageClass", rep(1:nAgeClass,2)),paste0("q",1:ncol)))

    quintList = list(M = quintMat[1:nAgeClass,], F = quintMat[nAgeClass+1:8,])
    
    return(quintList)
}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Compute Quintiles of Active Transport Time
#'
#' Compute Quintiles of Active Transport Time
#'
#' @param ITHIM A list of values generated by the \code{\link{computeMeanMatrices}}
#' 
#' @return A list of lists containing quintiles of active transport
#'     time and METs, by sex and age class.
#'
#' \item{ActiveTransportTime}{Foo}
#' \item{WalkingTime}{Foo}
#' \item{CyclingTime}{Foo}
#' \item{WalkingMET}{Foo}
#' \item{CyclingMET}{foo}
#' \item{TotalTravelMET}{foo}
#'
#' @seealso \code{\link{computeMeanMatrices}}
#' 
#' @export
getQuintiles <- function(ITHIM){
  with(ITHIM,{
    ActiveTransportTime <- computeQuintiles(means$meanActiveTransportTime, means$sdActiveTransportTime)
  WalkingTime <- list(M = ActiveTransportTime[["M"]] * (1-means$propTimeCycling[,"M"]), F = ActiveTransportTime[["F"]] * (1-means$propTimeCycling[,"F"]))
  CyclingTime <- list(M = ActiveTransportTime[["M"]] * (means$propTimeCycling[,"M"]), F = ActiveTransportTime[["F"]] * (means$propTimeCycling[,"F"]))
  WalkingMET <- list(M = means$meanWalkMET[,"M"]*WalkingTime[["M"]]/60, F = means$meanWalkMET[,"F"]*WalkingTime[["F"]]/60)
  CyclingMET <- list(M = means$meanCycleMET[,"M"]*CyclingTime[["M"]]/60, F = means$meanCycleMET[,"F"]*CyclingTime[["F"]]/60)
    TotalTravelMET <- list(M = WalkingMET[["M"]] + CyclingMET[["M"]], F = WalkingMET[["F"]] + CyclingMET[["F"]])

 return(list(ActiveTransportTime=ActiveTransportTime, WalkingTime=WalkingTime, CyclingTime=CyclingTime, WalkingMET=WalkingMET, CyclingMET = CyclingMET, TotalTravelMET = TotalTravelMET))})
}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Set Risk Ratios for Avctive Transport
#'
#' Set risk ratios for a list of diseases given MET exposure.  These
#' values are used to compute change in disease burden due to active
#' transport increase.
#'
#' @return A numerical vector of risk ratios given MET exposure
#'
#'
#' @export
createActiveTransportRRs <- function(){

    diseaseNames <- c("Breast Cancer","Colon Cancer","IHD","Depression","Dementia","Diabetes","Stroke")
    RR <- rep(0.98, length(diseaseNames))
    names(RR) <- diseaseNames
    return(RR)

}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Set Risk Ratios for Air Pollution
#'
#' Set risk ratios for a list of diseases given air pollution exposure.  These
#' values are used to compute change in disease burden due to air pollution.
#'
#' @return A numerical vector of risk ratios given air pollution exposure
#'
#' @note Hypertensive HD is done using a combination of RR by METs and RR by air
#'     pollution.
#' 
#' @export
createAirPollutionRRs <- function(){
    
    diseaseNames <- c("Lung Cancer","Acute resp infections","Inflammatory HD","Respiratory diseases")
    RR <- rep(1.02, length(diseaseNames))
    names(RR) <- diseaseNames
    return(RR)

}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Set Risk Ratios for Active Transport and Air Pollution
#'
#' Set risk ratios for a list of diseases given air pollution exposure and active transport exposure.  These
#' values are used to compute change in disease burden..
#'
#' @return A numerical vector of risk ratios given air pollution exposure and active transport exposure
#'
#' @export
createATandAPRRs <- function(){
    
    diseaseNames <- c("Hypertensive HD")
    RR <- rep(1.02, length(diseaseNames))
    names(RR) <- diseaseNames
    return(RR)

}
